# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SJCAM-UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from assets import icons_qrt
import sys
import subprocess
import cv2 as cv
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from backend import backend
import wmi
    

class Ui_MainWindow(object):
    def iniciar_camera(self):
        #self.backend.start()
        self.feedcamera.setPixmap(QtGui.QPixmap("assets/imagemindisponivel.png"))
        args = 'CamOpen.exe rtsp 192.168.100.1'
        subprocess.Popen(args, shell=True)
        print("Iniciar")

    def ImageUpdateSlot(self, Image):
        self.feedcamera.setPixmap(QPixmap.fromImage(Image))

    def semimagem(self):
        self.feedcamera.setPixmap(QtGui.QPixmap("assets/semimagem.png"))

    def parar_camera(self):
        self.semimagem()
        print("Parar")
        ti = 0
        name = 'CamOpen.exe'
        
        f = wmi.WMI()
        for process in f.win32_Process():
            if process.name == name:
                process.Terminate()
                print("Processo encontrado!! Encerrando...")
                ti +=1
                print("Encerrado!")

        if ti==0:
            print("Processo não encontrado.")
    



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 778)
        MainWindow.setMaximumSize(QtCore.QSize(1100, 800))
        MainWindow.setStyleSheet("*{\n"
"border: none;\n"
"background-color: rgb(227, 227, 227);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(1100, 800))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(0, 120, 1061, 491))
        self.frame_4.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_4)
        self.frame_3.setGeometry(QtCore.QRect(670, 50, 371, 361))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(0, 120, 371, 211))
        self.frame.setStyleSheet("*{\n"
"\n"
"    background-color: rgb(94, 0, 0);\n"
"border-radius:20px;\n"
"margin-left: auto;\n"
"margin-right: auto;\n"
"\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.iniciar = QtWidgets.QPushButton(self.frame)
        self.iniciar.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.iniciar.setFont(font)
        self.iniciar.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.iniciar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(0, 0, 0);\n"
"    margin-left: auto;\n"
"    margin-right: auto;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    \n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(0, 0, 0);\n"
"    margin-left: auto;\n"
"    margin-right: auto;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.iniciar.setObjectName("iniciar")
        self.verticalLayout_3.addWidget(self.iniciar)
        self.iniciar.clicked.connect(self.iniciar_camera)
        self.Parar = QtWidgets.QPushButton(self.frame)
        self.Parar.setMaximumSize(QtCore.QSize(500, 40))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setBold(True)
        font.setWeight(75)
        self.Parar.setFont(font)
        self.Parar.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.Parar.setMouseTracking(False)
        self.Parar.setTabletTracking(False)
        self.Parar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Parar.setAutoFillBackground(False)
        self.Parar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(170, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(0, 0, 0);\n"
"    margin-left: auto;\n"
"    margin-right: auto;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"    \n"
"    \n"
"    background-color: rgb(255, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-color: rgb(0, 0, 0);\n"
"    margin-left: auto;\n"
"    margin-right: auto;\n"
"    border-color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.Parar.setCheckable(False)
        self.Parar.setAutoDefault(False)
        self.Parar.setObjectName("Parar")
        self.Parar.clicked.connect(self.parar_camera)
        self.verticalLayout_3.addWidget(self.Parar)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(0, 10, 371, 101))
        self.label_3.setObjectName("label_3")
 
 
        self.backend = backend()
        self.backend.ImageUpdate.connect(self.ImageUpdateSlot)
        self.feedcamera = QtWidgets.QLabel(self.frame_4)
        self.feedcamera.setGeometry(QtCore.QRect(80, 70, 480, 360))
        self.feedcamera.setStyleSheet("")
        self.feedcamera.setText("Sem Imagem")
        self.feedcamera.setObjectName("feedcamera")

        

        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(20, 0, 1111, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(310, 10, 461, 91))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(4, 615, 1111, 151))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.iniciar.setText(_translate("MainWindow", "INICIAR"))
        self.Parar.setText(_translate("MainWindow", "PARAR"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/Icons/CAPTURAR.png\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/Icons/sjcam-app.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/Icons/footer.png\"/></p></body></html>"))
   
    



if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
